# Generated by Django 5.1.1 on 2024-09-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(blank=True, default="fallback.png", upload_to=""),
                ),
                ("cloth_brand", models.CharField(max_length=100)),
                ("cloth_color", models.CharField(max_length=100)),
                ("cloth_type", models.CharField(max_length=100)),
                (
                    "cloth_size",
                    models.CharField(
                        choices=[
                            ("Extra Small", "XS"),
                            ("small", "S"),
                            ("medium", "M"),
                            ("Large", "L"),
                            ("Extra Large", "XL"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
