# Generated by Django 5.1.1 on 2024-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_item",
            name="category",
            field=models.CharField(default="category", max_length=100),
        ),
    ]
