# Generated by Django 5.1.1 on 2024-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_user_item_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_item",
            name="banner",
            field=models.ImageField(
                blank=True, default="fallback.png", upload_to="uploads/"
            ),
        ),
        migrations.AlterField(
            model_name="user_item",
            name="category",
            field=models.CharField(
                choices=[
                    ("Shirts", "Shirts"),
                    ("Pants", "Pants"),
                    ("Innerwear", "Innerwear"),
                    ("Jeans", "Jeans"),
                    ("Jackets", "Jackets"),
                    ("Socks", "Socks"),
                    ("Wallets", "Wallets"),
                    ("Belts", "Belts"),
                    ("Ties", "Ties"),
                    ("Kerchiefs", "Kerchiefs"),
                    ("Tabs", "Tabs"),
                    ("Headphones", "Headphones"),
                    ("Cables", "Cables"),
                    ("Necklaces", "Necklaces"),
                    ("Rings", "Rings"),
                    ("Bracelets", "Bracelets"),
                    ("Fiction", "Fiction"),
                    ("Non-Fiction", "Non-Fiction"),
                    ("Biography", "Biography"),
                ],
                default="category",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="user_item",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xsmall", "XS"),
                    ("small", "S"),
                    ("medium", "M"),
                    ("large", "L"),
                    ("xlarge", "XL"),
                    ("xxlarge", "XXL"),
                ],
                max_length=100,
            ),
        ),
    ]
